set(CHIBIOS_CONTRIB_PORTS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ChibiOS-Contrib/os/hal/ports/STM32/LLD)
message(STATUS "CHIBIOS_CONTRIB_PORTS_DIR : " ${CHIBIOS_CONTRIB_PORTS_DIR})

# List of all the STM32F4XX platform files
# Can be found in platform.mk
set(CHIBIOS_CONTRIB_PLATFORM_SRC
    ${CHIBIOS_CONTRIB_PORTS_DIR}/CRCv1/hal_crc_lld.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/DMA2Dv1/hal_stm32_dma2d.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/FSMCv1/hal_fsmc.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/FSMCv1/hal_fsmc_sram.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/FSMCv1/hal_fsmc_sdram.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/FSMCv1/hal_fsmc.c 
    ${CHIBIOS_CONTRIB_PORTS_DIR}/FSMCv1/hal_fsmc_sram.c 
    ${CHIBIOS_CONTRIB_PORTS_DIR}/FSMCv1/hal_fsmc_sdram.c 
    ${CHIBIOS_CONTRIB_PORTS_DIR}/FSMCv1/hal_nand_lld.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/LTDCv1/hal_stm32_ltdc.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/TIMv1/hal_eicu_lld.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/TIMv1/hal_qei_lld.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/TIMv1/hal_timcap_lld.c
    ${CHIBIOS_CONTRIB_PORTS_DIR}/USBHv1/hal_usbh_lld.c)


set(CHIBIOS_CONTRIB_PLATFORM_INCLUDE_DIR
    ${CHIBIOS_CONTRIB_PORTS_DIR}/CRCv1
    ${CHIBIOS_CONTRIB_PORTS_DIR}/DMA2Dv1
    ${CHIBIOS_CONTRIB_PORTS_DIR}/FSMCv1
    ${CHIBIOS_CONTRIB_PORTS_DIR}/TIMv1
    ${CHIBIOS_CONTRIB_PORTS_DIR}/LTDCv1
    ${CHIBIOS_CONTRIB_PORTS_DIR}/USBHv1)
